# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

任务需求：
做一个关于redis的需求
1.根据唯一id来redis查数据，如果redis没有数据就去数据库查，同时把数据转成json放进redis，方便下次查数据
2.根据id.update数据，更新数据库的数据之后，在redis把old的数据替换成new Data
3.redis的计数器/投票功能: 用redsiTemplate的increment来计数,并且设置每个用户十分钟只能投票一次，过了十分钟再投票第二次
4.限流，根据用户ip作为id，访问一此添加一个int类型的value，到一定数量返回false
5.点赞
·某篇文章点赞数                  redis的value是HashMap<String,Set>类型,Map.key-String是articleId,Map.value-Set是用户id，这样一个用户只能点赞一次
·用户所有文章的点赞总数           给每个author都专门创建一个Map<String,Int>类型的计数数据，每次author有文章点赞，就给计数器的value+1
·用户点赞的文章                  跟某篇文章点赞数大同小异
·用户取消点赞                    根据用户id删除authorId里的点赞，和总点赞数，并且删除用户自身点赞记录
·规定时间持久化到sqlserver       定时任务
6.hash类型的数据，可以做购物车。redis.key是userSoleId,redis.valus是map类型，map.key是商品soleId，map.value是数量。

这个项目连接的公司的数据库，不知道Mysql能不能让两个电脑连接


幂等校验
悲观锁 乐观锁  redis分布式锁
6.微服务
手写冒泡排序
Stream
单例模式
消息中间件的需求
用RabbitMQ
Linux
诺依
Jwt
一个项目连接两个数据库，好像只能用传统dao，不能用jpa
分布式项目

