spring:
  datasource:
    url: jdbc:sqlserver://172.25.1.128:1433;DatabaseName=test_yum_central_portal
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ttsweb
    password: China8620

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 8080
